
name: Update Entries from PDF

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 10 * * 3'  # Every Wednesday at 10:00 UTC

jobs:
  parse-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - - name: Set up Python
        uses: actions/setup-python@v4
        with:
        python-version: 3.10

      - name: Install dependencies
        run: |
          pip install google-api-python-client google-auth fitz PyMuPDF

      - name: Run PDF parser
        env:
          GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        run: python parse_pdf.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data/entries.json data/last_run.json
          git commit -m "Update entries from latest press review" || echo "No changes to commit"
          git push
